"""Small Slurm adapter for running a prepared simulation checkout in place."""

from __future__ import annotations

import shlex
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

from .artifacts import canonical_json, discover_artifacts, source_digest, verify_artifact
from .config import CampaignConfig, as_serializable
from .planning import Plan, Task, read_plan, read_state, write_plan


class ClusterError(RuntimeError):
    """Cluster scripts or submission prerequisites are invalid."""


@dataclass(frozen=True)
class RenderedCluster:
    root: Path
    script: Path
    task_file: Path
    doctor_script: Path
    task_count: int
    stage_scripts: dict[str, Path]
    stage_task_files: dict[str, Path]


def _shell(value: str | Path) -> str:
    return shlex.quote(str(value))


def _header(config: CampaignConfig, stage: str, *, array_size: int | None) -> str:
    array_line = f"#SBATCH --array=0-{array_size - 1}\n" if array_size is not None else ""
    log_suffix = "%A_%a" if array_size is not None else "%j"
    return f"""#!/usr/bin/env bash
# Generated by dcft. This job executes the configured checkout in place.
#SBATCH --job-name=dcft-{config.campaign.name}-{stage}
#SBATCH --partition={config.cluster.partition}
#SBATCH --account={config.cluster.account}
#SBATCH --time={config.cluster.time_limit}
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={config.cluster.cpus_per_task}
#SBATCH --mem={config.cluster.memory}
{array_line}#SBATCH --output={config.campaign.output_root}/cluster/logs/{stage}_{log_suffix}.out
#SBATCH --error={config.campaign.output_root}/cluster/logs/{stage}_{log_suffix}.err

"""


def _task_bootstrap(config: CampaignConfig, *, array: bool) -> str:
    task_suffix = "${SLURM_ARRAY_TASK_ID}" if array else "singleton"
    return f"""set -euo pipefail
export PATH="${{HOME}}/.local/bin:${{HOME}}/.cargo/bin:${{PATH}}"
PROJECT_ROOT={_shell(config.campaign.project_root)}
CONFIG_PATH={_shell(config.source)}
DCFT="$PROJECT_ROOT/.venv/bin/dcft"
TASK_SCRATCH={_shell(config.campaign.scratch_root)}/"${{SLURM_JOB_ID}}"/{task_suffix}

test -x "$DCFT"
mkdir -p "$TASK_SCRATCH" {_shell(config.campaign.output_root / "cluster" / "logs")}
export RAYON_NUM_THREADS="${{SLURM_CPUS_PER_TASK}}"
export MPLCONFIGDIR="$TASK_SCRATCH/matplotlib"
export DCFT_TASK_SCRATCH="$TASK_SCRATCH"
cd "$PROJECT_ROOT"
"""


def _write_array_stage(
    config: CampaignConfig,
    root: Path,
    stage: str,
    tasks: list[Task],
) -> tuple[Path, Path]:
    task_file = root / f"{stage}-tasks.txt"
    task_file.write_text("".join(f"{task.task_id}\n" for task in tasks))
    script = root / f"{stage}.sbatch"
    script.write_text(
        _header(config, stage, array_size=len(tasks))
        + _task_bootstrap(config, array=True)
        + f"""TASK_FILE={_shell(task_file)}
TASK_ID=$(sed -n "$((SLURM_ARRAY_TASK_ID + 1))p" "$TASK_FILE")
test -n "$TASK_ID"
"$DCFT" campaign run --config "$CONFIG_PATH" --executor local --workers "$SLURM_CPUS_PER_TASK" --task-id "$TASK_ID"
"""
    )
    script.chmod(0o755)
    return script, task_file


def _write_singleton_stage(
    config: CampaignConfig,
    root: Path,
    stage: str,
    command: str,
) -> Path:
    script = root / f"{stage}.sbatch"
    script.write_text(
        _header(config, stage, array_size=None)
        + _task_bootstrap(config, array=False)
        + f'"$DCFT" campaign {command} --config "$CONFIG_PATH"\n'
    )
    script.chmod(0o755)
    return script


def render_cluster(config: CampaignConfig, output: Path | None = None) -> RenderedCluster:
    plan = write_plan(config)
    root = (
        output.expanduser().resolve()
        if output is not None
        else (config.campaign.output_root / "cluster" / "rendered").resolve()
    )
    root.mkdir(parents=True, exist_ok=True)
    (config.campaign.output_root / "cluster" / "logs").mkdir(parents=True, exist_ok=True)
    stages = {
        kind: [task for task in plan.tasks if task.kind == kind]
        for kind in ("clean", "exact", "mc", "merge")
    }
    stage_scripts: dict[str, Path] = {}
    stage_task_files: dict[str, Path] = {}
    for stage, tasks in stages.items():
        if tasks:
            script, task_file = _write_array_stage(config, root, stage, tasks)
            stage_scripts[stage] = script
            stage_task_files[stage] = task_file
    stage_scripts["analysis"] = _write_singleton_stage(config, root, "analysis", "analyze")
    stage_scripts["validation"] = _write_singleton_stage(config, root, "validation", "validate")

    execution_tasks = [
        task for task in plan.tasks if task.kind in {"clean", "exact", "mc", "merge"}
    ]
    (root / "dag.json").write_bytes(
        canonical_json(
            {
                "plan_version": plan.plan_version,
                "config_digest": plan.config_digest,
                "rendered_source_digest": source_digest(config.campaign.project_root),
                "execution": {
                    "checkout_mode": "in-place",
                    "config_path": str(config.source),
                    "output_root": str(config.campaign.output_root),
                    "project_root": str(config.campaign.project_root),
                    "scratch_root": str(config.campaign.scratch_root),
                    "parallelism": as_serializable(config)["execution"],
                    "cluster": as_serializable(config)["cluster"],
                },
                "stage_dependencies": {
                    "clean": [],
                    "exact": [],
                    "mc": ["clean"],
                    "merge": ["mc"],
                    "analysis": ["clean", "exact", "merge"],
                    "validation": ["analysis"],
                },
                "tasks": [
                    {
                        "task_id": task.task_id,
                        "kind": task.kind,
                        "dependencies": list(task.dependencies),
                    }
                    for task in plan.tasks
                ],
            }
        )
    )
    doctor_script = root / "doctor.sh"
    doctor_script.write_text(
        f"""#!/usr/bin/env bash
set -euo pipefail
export PATH="${{HOME}}/.local/bin:${{HOME}}/.cargo/bin:${{PATH}}"
PROJECT_ROOT={_shell(config.campaign.project_root)}
test -f "$PROJECT_ROOT/uv.lock"
test -f "$PROJECT_ROOT/Cargo.lock"
test -x "$PROJECT_ROOT/.venv/bin/dcft"
command -v sbatch
"$PROJECT_ROOT/.venv/bin/python" -c 'from dcft import _core; assert {"tnmc", "tnmc-global"} <= set(_core.update_registry())'
echo "DCFT checkout and Slurm client are ready."
"""
    )
    doctor_script.chmod(0o755)
    representative = "mc" if "mc" in stage_scripts else next(iter(stage_task_files))
    return RenderedCluster(
        root=root,
        script=stage_scripts[representative],
        task_file=stage_task_files[representative],
        doctor_script=doctor_script,
        task_count=len(execution_tasks),
        stage_scripts=stage_scripts,
        stage_task_files=stage_task_files,
    )


def doctor(config: CampaignConfig) -> dict[str, Any]:
    """Check the prepared checkout; submission additionally requires ``sbatch``."""
    executable = config.campaign.project_root / ".venv" / "bin" / "dcft"
    checks = {
        "runtime_ready": executable.is_file(),
        "uv_available": shutil.which("uv") is not None,
        "cargo_available": shutil.which("cargo") is not None,
        "slurm_client_available": shutil.which("sbatch") is not None,
        "uv_lock_present": (config.campaign.project_root / "uv.lock").is_file(),
        "cargo_lock_present": (config.campaign.project_root / "Cargo.lock").is_file(),
        "project_scratch_separate": (
            config.campaign.project_root.resolve() != config.campaign.scratch_root.resolve()
        ),
        "account_configured": bool(config.cluster.account)
        and not config.cluster.account.startswith("SET_"),
    }
    runtime_required = (
        "runtime_ready",
        "uv_lock_present",
        "cargo_lock_present",
        "project_scratch_separate",
        "account_configured",
    )
    return {
        "status": "ready" if all(checks[name] for name in runtime_required) else "failed",
        "checks": checks,
        "runtime": str(executable),
        "note": "Run `uv sync --frozen` once in the checkout if runtime_ready is false.",
    }


def _require_submit_ready(config: CampaignConfig) -> None:
    result = doctor(config)
    checks = cast(dict[str, bool], result["checks"])
    required = (
        "runtime_ready",
        "slurm_client_available",
        "uv_lock_present",
        "cargo_lock_present",
        "project_scratch_separate",
        "account_configured",
    )
    failed = [name for name in required if not checks[name]]
    if failed:
        raise ClusterError(f"cluster submission prerequisites failed: {failed}")


def _submit_script(
    script: Path,
    *,
    indices: list[int] | None = None,
    dependencies: list[str] | None = None,
) -> str:
    command = ["sbatch", "--parsable"]
    if indices is not None:
        array = ",".join(str(index) for index in indices)
        command.append(f"--array={array}")
    if dependencies:
        command.append(f"--dependency=afterok:{':'.join(dependencies)}")
    command.append(str(script))
    process = subprocess.run(command, check=True, capture_output=True, text=True)
    return process.stdout.strip().split(";")[0]


def _current_task_ids(config: CampaignConfig, state: dict[str, Any]) -> set[str]:
    digest = source_digest(config.campaign.project_root)
    artifacts = {
        artifact.artifact_id: artifact
        for artifact in discover_artifacts(config.campaign.output_root)
    }
    current: set[str] = set()
    for task_id, task_state in cast(dict[str, dict[str, Any]], state["tasks"]).items():
        artifact_ids = [str(value) for value in task_state["artifacts"]]
        if task_state["status"] != "complete" or not artifact_ids:
            continue
        try:
            valid = all(
                artifact_id in artifacts
                and artifacts[artifact_id].manifest["source_digest"] == digest
                and verify_artifact(artifacts[artifact_id].path)["status"] == "valid"
                for artifact_id in artifact_ids
            )
        except Exception:
            valid = False
        if valid:
            current.add(task_id)
    dependencies = {task.task_id: set(task.dependencies) for task in read_plan(config).tasks}
    changed = True
    while changed:
        changed = False
        for task_id in tuple(current):
            if not dependencies[task_id] <= current:
                current.remove(task_id)
                changed = True
    return current


def _pending_indices(plan: Plan, current_task_ids: set[str], kind: str) -> list[int]:
    tasks = [task for task in plan.tasks if task.kind == kind]
    return [index for index, task in enumerate(tasks) if task.task_id not in current_task_ids]


def _submit_array(
    rendered: RenderedCluster,
    plan: Plan,
    current: set[str],
    jobs: dict[str, str],
    stage: str,
    dependencies: list[str],
) -> None:
    indices = _pending_indices(plan, current, stage)
    if indices:
        jobs[stage] = _submit_script(
            rendered.stage_scripts[stage],
            indices=indices,
            dependencies=dependencies,
        )


def _submit_dag(config: CampaignConfig) -> dict[str, Any]:
    rendered = render_cluster(config)
    plan = read_plan(config)
    state = read_state(config)
    current = _current_task_ids(config, state)
    jobs: dict[str, str] = {}
    _submit_array(rendered, plan, current, jobs, "clean", [])
    _submit_array(rendered, plan, current, jobs, "exact", [])
    _submit_array(
        rendered,
        plan,
        current,
        jobs,
        "mc",
        [jobs["clean"]] if "clean" in jobs else [],
    )
    _submit_array(
        rendered,
        plan,
        current,
        jobs,
        "merge",
        [jobs["mc"]] if "mc" in jobs else [],
    )

    analysis_task = next(task for task in plan.tasks if task.kind == "analysis")
    validation_task = next(task for task in plan.tasks if task.kind == "validation")
    compute_jobs = [jobs[name] for name in ("clean", "exact", "mc", "merge") if name in jobs]
    if analysis_task.task_id not in current:
        jobs["analysis"] = _submit_script(
            rendered.stage_scripts["analysis"], dependencies=compute_jobs
        )
    if validation_task.task_id not in current:
        validation_dependencies = [jobs["analysis"]] if "analysis" in jobs else compute_jobs
        jobs["validation"] = _submit_script(
            rendered.stage_scripts["validation"], dependencies=validation_dependencies
        )
    return {
        "jobs": jobs,
        "root_job_id": jobs.get("validation", jobs.get("analysis", next(iter(jobs.values()), ""))),
        "rendered_root": str(rendered.root),
        "resource_shape": {
            "cpus_per_task": config.cluster.cpus_per_task,
            "mc_chunks_per_point": config.execution.mc_chunks,
            "memory_per_task": config.cluster.memory,
            "time_limit": config.cluster.time_limit,
        },
    }


def submit(config: CampaignConfig) -> dict[str, Any]:
    _require_submit_ready(config)
    return _submit_dag(config)


def cluster_status(job_id: str) -> dict[str, Any]:
    if not job_id or any(character not in "0123456789_" for character in job_id):
        raise ClusterError("job id must contain only digits and underscore")
    command = ["squeue", "--noheader", "--jobs", job_id, "--format", "%i|%T|%M|%R"]
    process = subprocess.run(command, check=False, capture_output=True, text=True)
    if process.returncode != 0:
        raise ClusterError(process.stderr.strip() or "squeue failed")
    rows = [line.split("|") for line in process.stdout.splitlines() if line]
    return {
        "job_id": job_id,
        "tasks": [
            {"id": row[0], "state": row[1], "elapsed": row[2], "reason_or_node": row[3]}
            for row in rows
        ],
    }


def resume(config: CampaignConfig) -> dict[str, Any]:
    _require_submit_ready(config)
    result = _submit_dag(config)
    result["status"] = "submitted" if result["jobs"] else "nothing-to-resume"
    return result
